setlocal wrap
setlocal wrapmargin=2
setlocal textwidth=72
setlocal spell
setlocal formatoptions+=l
setlocal colorcolumn=73
setlocal softtabstop=3
setlocal tabstop=3
setlocal shiftwidth=3
setlocal expandtab
