# ssh aliases
alias sshm='ssh -p 27148 meldanya.se'
alias sshdsek='ssh meldanya@snejk.dsek.lth.se'
alias sshlth='ssh dt09ej7@login.student.lth.se'

# mac specific aliases
alias enabledashboard='defaults write com.apple.dashboard mcx-disabled -boolean NO'
alias disdashboard='defaults write com.apple.dashboard mcx-disabled -boolean YES'
alias showhidden='defaults write com.apple.finder AppleShowAllFiles TRUE; killall Finder'
alias hidehidden='defaults write com.apple.finder AppleShowAllFiles FALSE; killall Finder'
alias hibernate='sudo pmset -a hibernatemode'
alias listhibernate='sudo pmset -g | grep hibernatemode'

# shortcut commands
alias vim='mvim -v'
alias ll='ls -al'
alias l='ls -l'
alias cc='cc -std=c99 -pedantic -Wextra'
alias clean='make clean' # not sure if I should keep this, rarely use it
alias matlab='matlab -nodesktop -nojvm -nosplash'
