# make Terminal.app display colors
export CLICOLOR=1

# some paths
export PATH=/usr/local/sbin:/usr/local/bin:/Applications/android-sdk/platform-tools:/Applications/android-sdk/tools:$PATH
export PATH=~/bin:$PATH

# Path for node.js
export NODE_PATH=/usr/local/lib/node:/usr/local/lib/node_modules

export EDITOR='vim'

# load rvm into shell session
[[ -s "/Users/erik/.rvm/scripts/rvm" ]] && source "/Users/erik/.rvm/scripts/rvm"
# [[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

export LANG=en_US.UTF-8

# Include git bash completion
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	. /usr/local/etc/bash_completion.d/git-completion.bash
fi

# Include tmux bash completion
if [ -f /usr/local/etc/bash_completion.d/tmux ]; then
	. /usr/local/etc/bash_completion.d/tmux
fi

# Include ack bash completion
if [ -f /usr/local/etc/bash_completion.d/ack.bash_completion.sh ]; then
	. /usr/local/etc/bash_completion.d/ack.bash_completion.sh
fi

# Include my aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# Include promt settings
if [ -f ~/.bash_ps1 ]; then
	. ~/.bash_ps1
fi
